### ISSUE TITLE
Certain programs always start on VD1

### ISSUE THREAD

**Issue by thany** [eksime/VDesk#39] opened 2017-10-24 15:42 UTC
One program I'm trying to start on VD2 is Whatsapp (the desktop app, not the browser app). But for whatever reason, it always starts on VD1.

Here's the command:
```
vdesk on:2 noswitch:true run:C:\Users\thany\AppData\Local\WhatsApp\WhatsApp.exe
```
It starts fine, but not in VD2, but on VD1. VD2 does exist already.

Tried on Windows 10 x64 with Fall Creators update.

**Comment by eksime** [comment] 2017-10-24 16:09
(Duplicate of #15 )

I'm not certain how WhatsApp creates its windows, but for the most part issue with window placement are down to the program creating the windows via a child process or doing other strange things on startup.

Try without the noswitch:true, and see if it is started on the correct desktop. If so, then it is almost certainly down to whatsapp creating its windows in a manner vdesk can't handle.

**Closed by eksime** 2017-10-24 16:09 UTC

**Comment by cruzer619** [comment] 2017-10-24 19:20
Yes you can get this to work just fine with vdesk.  your just using the wrong executable.

This is what I use : vdesk on:2 run:"C:\Users\thany\AppData\Local\WhatsApp\Update.exe" --processStart Whatsapp.exe

Hope that helps.

Rich

**Comment by thany** [comment] 2017-10-25 08:53
Thanks, @cruzer619 but adding the `noswitch:true` flag makes the app start on VD1 again.

It seems there might be something fundamentally wrong with the noswitch flag. It causes so many problems :(
