### ISSUE TITLE
using noswitch:true is giving me errors

### ISSUE THREAD

**Issue by MassiveAtoms** [eksime/VDesk#53] opened 2018-07-15 15:14 UTC
OS: Windows 10 version 1803 build 17134.112
Vdesk version : 1.1.2

Behaviour: 
`vdesk on:2 run:<command>` works perfectly fine, but 
`vdesk on:2 noswitch:true run:<command>`  opens up the program in whatever desktop I'm currently in instead of the specified desktop, and gives the following error:

![capture](https://user-images.githubusercontent.com/31139696/42735331-68618ad4-8841-11e8-8b0e-60144720a29c.PNG)

I can close the error box and the program behaves as expected, it's just in the wrong desktop.

**Comment by eksime** [comment] 2018-07-22 15:37
Caused by the 1803 update, fixed in 8c1bf48, updating to version 1.2.0 should fix this issue.

**Closed by eksime** 2018-07-22 15:37 UTC

**Comment by avindra** [comment] 2018-10-03 17:36
I'm getting this error with 1.2.0 (using Windows 10 Version 1709 build 16299.611)

![image](https://user-images.githubusercontent.com/126848/46428116-2097f080-c711-11e8-8754-126feadd8f6c.png)


Can we reopen this issue or should I file a new one?
